version: "3.7"
services: 
   loopix_server:
     command: "tail -F /dev/null" 
     image: loopix_server
     build:
        context: ..
        dockerfile: docker/server/Dockerfile
   mix-L1-P1:
      build: 
        context: ..
        dockerfile: docker/mixes/Dockerfile
      image: loopix-mix
      environment: 
        - HOST=mix-L1-P1
        - ID=0
      ports: [8100:9999]
      networks:
        - my-shared-network
      volumes: 
        - my-global-volume:/volumes/global
      depends_on:
       - loopix_server
   mix-L2-P1:
      build: 
        context: ..
        dockerfile: docker/mixes/Dockerfile
      image: loopix-mix
      environment: 
        - HOST=mix-L2-P1
        - ID=1
      ports: [8200:9999]
      networks:
        - my-shared-network
      volumes: 
        - my-global-volume:/volumes/global
      depends_on:
       - loopix_server
   mix-L3-P1:
      build: 
        context: ..
        dockerfile: docker/mixes/Dockerfile
      image: loopix-mix
      environment: 
        - HOST=mix-L3-P1
        - ID=2
      ports: [8300:9999]
      networks:
        - my-shared-network
      volumes: 
        - my-global-volume:/volumes/global
      depends_on:
       - loopix_server
   provider-1:
      build: 
        context: ..
        dockerfile: docker/provider/Dockerfile
      image: loopix-provider
      environment: 
        - HOST=Provider-1
        - ID=9000
      ports: [9000:9999]
      networks:
        - my-shared-network
      volumes: 
        - my-global-volume:/volumes/global
      depends_on:
       - loopix_server
networks:
          my-shared-network: {}
volumes:
        my-global-volume:
